### ISSUE TITLE
sameDomain not defined

### ISSUE THREAD

**Issue by magisterquis** [abidibo/moopopup#1]
When a popup with the following options is created, closed, and the overlay clicked, chrome's javascript console says complains that `sameDomain` is not defined.
    {
        title:          "Gender Popup Window",
        draggable:      false,
        resizable:      false,
        overlay_click_close_window:     false,
        html_node:      "gender_div",
    }

**Comment by magisterquis** [comment]
Solution is to add `.this` in line 132 of moopopup.js:
`if(sameDomain(myFrame)) {` -> `if(this.sameDomain(myFrame)) {`

**Comment by abidibo** [comment]
thanks for the advise, it will be fixed in the next release.
