### ISSUE TITLE
click function on radio button in IE11

### ISSUE THREAD

**Issue by Stilos** [abidibo/moopopup#2]
Hi, i have a big issue with your library under IE11 (i know you didn't test you library under it but maybe you can solve this).

I have popup with two radio buttons that have click="someFunc()" inside <input TAG.
This causes them to be rendered as text fields (Seriously).
If i try to add click function by MooTools or even pure JS it just doesn't register the event.

Any solution to this one ?

**Comment by abidibo** [comment]
Some information missing here. How you set the popup content, as DOMElement, as string, with ajaxRequest? Please try to setup a jsfiddle or codepen example. I'll help you fixing this.

**Comment by Stilos** [comment]
Hi, thanks for the fast reply. This will be very hard to do as i am using this iside huuuge project with tons of libraries. 

When i have extracted your libraries and made a test on sigle element it works fine so i need to look somewhere else.

Sorry for making pointless Issue .

**Comment by abidibo** [comment]
Ok, you're welcome.
Hope you find your bug.
